version: '3.8'
services:
  postgres:
    image: postgres:13.4-alpine
    restart: always
    environment: 
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=satixnimble
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports: 
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  # app:
  #   image: golang:1.17.0-alpine3.14
  #   volumes: 
  #     - .:/go/src/go-with-compose
  #   working_dir: /go/src/go-with-compose
  #   command: go run .
